version: "3"
services:
  develop:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
      - 9929:9929
      - 9230:9230
    volumes:
      - /opt/incremental_blog/node_modules
      - ./app:/opt/incremental_blog
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/